### PR TITLE
Improved syntax highlighting

### PR DESCRIPTION
**Pull request by Leandros**
Few additions:
- TODO / FIXME / XXX now recognized in comments
- #if / #else # elseif now properly recognizes the next token correctly
- improved version compatability
- improved formatting

### CODE REVIEW

**Comment by dummyunit** [comment]
Thank you for your contribution.

There are some minor issues, I will fix them after integrating your changes:
1. `delcommand HiLink` is missing.
2. Highlight for token after after `fbIfElse` overrides `fbPredefSymbol`.
3. Tokens after `#else` and `#endif` shouldn't be highlighted (I plan to later add `Error` highlight for such cases).

**Comment by Leandros** [comment]
Good catch!

Another great case for an error highlight (and shouldn't be to complicated) is to only highlight options inside the correct function blocks.

```
Alias('foo')
{
    .Compiler = 'bar'
    .Targets = 'bar'
}
```

wouldn't highlight `.Compiler` as a keyword, but as a simple variable. `.Targets`, however, would be highlighted due to being valid inside an `Alias` function call. This could improve spotting misnamed properties of functions.

**Comment by dummyunit** [comment]
I think highlighting properties _only_ in appropriate functions would be bad, because using them at the global scope or inside structs is perfectly valid. Highlighting them in functions that doesn't use them would be better.

And I think case of misspelled properties is is already covered. For example `.Complier` is highlighted as any other user variable (`fbVariableName`) that should tip off the user.

**Comment by Leandros** [comment]
> Highlighting them in functions that doesn't use them would be better.

You mean highlighting them as an error? I thought of that as well, but it would erroneously highlight user variables as errors, even though it's perfectly valid to use a variable called `.Compiler` in a function not making use of it (for example for prepending it to other variables, or for dynamically creating other variables).

Unfortunately your criticism is absolutely correct, too. I haven't thought of the case.

> And I think case of misspelled properties is is already covered. For example .Complier is highlighted as any other user variable (fbVariableName) that should tip off the user.

True.

**Pull request merged**
